/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorSensorAbstraction_.c
 * Generated on: Sun Jul 21 19:31:3 EEST
 ********************************************************************/

#include "string.h"
#include "Rte_DoorSensorAbstraction.h"


extern My_uint8 Door_Get_state_PP_SR_door_state_DoorState;


const Rte_CDS_DoorSensorAbstraction Rte_Instance_DoorSensorAbstraction = {
&Door_Get_state_PP_SR_door_state_DoorState
};

const Rte_CDS_DoorSensorAbstraction * const Rte_Inst_DoorSensorAbstraction = &Rte_Instance_DoorSensorAbstraction;




void Rte_IWrite_DoorSensorAbstraction_Door_Get_state_PP_SR_door_state_DoorState (My_uint8 DoorState)
{
	(Rte_Inst_DoorSensorAbstraction)->Door_Get_state_PP_SR_door_state_DoorState->value = DoorState;
}
My_uint8* Rte_IWriteRef_DoorSensorAbstraction_Door_Get_state_PP_SR_door_state_DoorState(void)
{
	return &(Rte_Inst_DoorSensorAbstraction)->Door_Get_state_PP_SR_door_state_DoorState->value;
}
