/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLockIndication_SWC_Type.h
 * Generated on: Sun Jul 21 19:31:3 EEST
 ********************************************************************/

#ifndef RTE_DOORLOCKINDICATION_SWC_TYPE_H
#define RTE_DOORLOCKINDICATION_SWC_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define My_uint8_LowerLimit  (0U)
#define My_uint8_UpperLimit (255U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOORLOCKINDICATION_SWC_TYPE_H */
